[package]

authors = ["tanaca <jtanacar@gmail.com>"]
build = "./src/main.rs"
edition = "2018"
name = "rust_studies"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
